Azpen/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('doctor/',include('doctor.urls')),
    path('',include('patient.urls'))
]

doctor/urls.py
from django.urls import path
from . import views
app_name='doctor'
urlpatterns=[
    path('doctorlogin/',views.doctorlogin,name='doctorlogin'),
    path('patientlist',views.patientlist,name='patientlist'),
    path('update_status_of_patient/<int:patient_id>',views.update_status_of_patient,name='update_status_of_patient'),
    path('remove_appointment/<int:appointment_id>,',views.remove_appointment,name='remove_appointment')
]

patient/urls.py
from django.urls import path
from . import views
app_name='patient'
urlpatterns=[
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup'),
    path('booking/',views.booking,name='booking'),
    path('',views.home,name='home'),
    path('list/',views.list,name='list')
    
]

doctor/models.py
from django.db import models

# Create your models here.
class Doctor(models.Model):
    name=models.TextField(max_length=50,null=True)
    password=models.TextField(max_length=50,null=True)
    specialization=models.TextField(max_length=50,null=True)
    def __str__ (self):
        return self.name

patient/models.py
from django.db import models
from doctor.models import*
# Create your models here.
class Patient(models.Model):
    name=models.TextField(max_length=100,null=True)
    email=models.TextField(max_length=100,null=True)
    repass=models.TextField(max_length=100,null=True)
class Appointment(models.Model):
    name=models.TextField(max_length=50,null=True)
    date=models.DateField(max_length=50,null=True)
    time=models.TimeField(max_length=50,null=True)
    message=models.TextField(max_length=500,null=True)
    doctor=models.ForeignKey(Doctor,on_delete=models.CASCADE)
    status=models.TextField(max_length=20)

doctor/views.py
from django.shortcuts import render,redirect
from . models import*
from patient.models import *
# Create your views here.
def patientlist(request):
    doc=Doctor.objects.all()
    doctorid=request.session.get('docid')

    appointment = Appointment.objects.filter(doctor=doctorid)
    return render(request,'doctor/patientlist.html',{'appointments':appointment})
def doctorlogin(request):
    if request.method=='POST':
        name=request.POST['name']
        password=request.POST['password']
        try:
            doctor = Doctor.objects.get(name=name, password=password)
            request.session['docid'] =doctor.id
            return redirect('doctor:patientlist')
        except Doctor.DoesNotExist:
            return render(request,'doctor/doctorlogin.html', {'msg': 'invalid credentials'})
    return render(request,'doctor/doctorlogin.html')
def update_status_of_patient(request,patient_id):
    appointment=Appointment.objects.get(id=patient_id)
    
    appointment.status='confirmed'
    appointment.save()
    return redirect('doctor:patientlist')
def remove_appointment(request,appointment_id):
    Appointment.objects.get(id=appointment_id).delete()
    return redirect('doctor:patientlist')

    

patient/views.py
from django.shortcuts import render,redirect
from .models import*
# Create your views here.
def home(request):
    return render(request,'patient/home.html')
def booking(request):
    doctors=Doctor.objects.all()
    if request.method=='POST':
        name=request.POST['name']
        date=request.POST['date']
        time=request.POST['time']
        message=request.POST['message']
        doctor_id=request.POST['doctor']
        doctor=Doctor.objects.get(id=doctor_id)
        appointment=Appointment(name=name,date=date,time=time,doctor=doctor,message=message,status='waiting')
        appointment.save()
        return render(request,'patient/booking.html',{'msg':'your Appointment updation will be added in APPOINTMENT LIST'})
    return render(request,'patient/booking.html',{'doctors':doctors})
def login(request):
    if request.method=='POST':
        email=request.POST['email']
        password=request.POST['password']
        if Patient.objects.filter(email=email,repass=password).exists():
            return render(request,'patient/booking.html')
        else:
            return render(request,'patient/login.html',{'msg':'invalid email or password?'})
    return render(request,'patient/login.html')
def signup(request):
    if request.method=='POST':
        name=request.POST['name']
        email=request.POST['email']
        password=request.POST['password']
        patient=Patient(name=name,email=email,repass=password)
        patient.save()
        return redirect('patient:login')
    return render(request,'patient/signup.html')
def list(request):
    patient=Appointment.objects.filter(status='confirmed')
    return render(request,'patient/list.html',{'patient':patient})

doctor/templates/doctor/doctorlogin.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Hospital Management</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'patient:home' %}">Home</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'doctor:patientlist' %}">patient list</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'doctor:doctorlogin' %}">login</a>
                  </li><li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">Admin login</a>
                  </li>
                 
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
    </div>



   <div class="row" id="row1">
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Name</label>
          <input type="name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
       
        
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
   </div>

</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

doctor/templates/doctor/patientlist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        table{
            width: 600px;
        
            border: 3px solid black;
            text-align: center;
        }
        table th, td{
            border: 4px solid black;
        }
    
    </style>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Hospital Management</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'patient:home' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">about us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'admin:index' %}">admin login</a>
              </li>
          </div>
        </div>
      </nav>
    <div class="row">
        <div class="col-12">
        <form action="" method="post">
            <table>
                <tr>
                    <th>Name</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Message</th>
                    <th>Status</th>
                    <th>Remove</th>    
                </tr>
                {% for i in appointments %}
                <tr>
                  <th id="row">{{i.name}}</th>
                  <td>{{i.date}}</td>
                  <td>{{i.time}}</td>
                  <td>{{i.message}}</td>
                  <td><a href="{% url 'doctor:update_status_of_patient' i.id %}" type="submit" class="btn-outline-dark">{{i.status}}</a></td>
                  <td><a href="{% url 'doctor:remove_appointment' i.id %}" class="btn btn-light">remove</a></td>
                </tr>
                {% endfor %}   
            </table>
        </form>
        </div>
    </div>
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

patient/templates/patient/booking.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
      #row2{
        margin-left: 400px;
        width: 500px;
        margin-top: 50px;
      }
      #row2 button{
        margin-top: 10px;
      }
    </style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-lg bg-body-tertiary">
                <div class="container-fluid">
                  <a class="navbar-brand" href="#">Hospital Management</a>
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'patient:home' %}">Home</a>
                      </li>
                      
                      <li class="nav-item">
                        <a class="nav-link" href="{% url 'patient:login' %}">login</a>
                      </li>
                     
                    
                    </ul>
                    <form class="d-flex" role="search">
                      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                      <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                  </div>
                </div>
              </nav>

        </div>
        <div class="row" id="row2">
          <form action="" method="post">
            {% csrf_token %}
            <h1>Get an appointment</h1>

            <table style="margin-top: 20px;">
              <tr>
                <th><label for="formGroupExampleInput" class="form-label">Full Name</label></th>
              </tr>
              <tr>
                <th><input type="text" class="form-control" id="formGroupExampleInput" placeholder="enter your name" name="name"></th>
              </tr>
              
              
              <tr>
                <th><label for="">Select doctor</label></th>
              </tr>
              <tr>
                <th><select class="form-select" aria-label="Default select example" name="doctor">
                  <option selected>Select the doctor</option>
                  {% for doc in doctors %}
                  <option value="{{doc.id}}">Dr {{doc.name}} {{doc.specialization}}</option>
                  
                  {% endfor %}
                </select></th>
              </tr>
              <tr>
                <th><label for="birthday">Date:</label></th>
              </tr>
              <tr>
                <th><input type="date" id="birthday" name="date"></th>
              </tr>
              <tr>
                <th><label for="appt">Select a time:</label></th>
              </tr>
              <tr>
                <th><select class="form-control" name="time" id="">
                  <option value="09:00:00">9:00am</option>
                  <option value="10:00:00">10:00am</option>
                  <option value="11:00:00">11:00am</option>
                  <option value="12:00:00">12:00pm</option>
                  <option value="13:00:00">1:00pm</option>
                </select></th>
              </tr>
              <tr>
                <th><label for="exampleFormControlTextarea1" class="form-label">type your message here</label></th>
              </tr>
              <tr>
                <th><textarea class="form-control" placeholder="text" id="exampleFormControlTextarea1" rows="3" name="message"></textarea></th>
              </tr>
              <tr>
                <th> <button type="submit" class="btn btn-primary">Submit</button></th>
              </tr>
          </table>
        </form>

          </div>
        </div>
    </div>
</body>
</html>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

{% block content %}
{% endblock %}

patient/templates/patient/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <style>
    #row2 h1{
      text-align: center;
      padding-top: 100px;
      height: 350px;
      background-color: black;
    }
    #row3 h2{
      text-align: center;
      
    }
    #row5 h2{
       text-align: center;
       background-color: aqua;
    }
    #row5 input{
      width: 250px;
      border: 1px solid black;
      margin-left: 500px;

    }
    #row5 label{
      margin-left: 500px;
      
    }
    #row5 button{
      margin-left: 600px;
    }
  </style>
</head>
<body>
    <div class="container-fluid">

      <div class="row">
        <div class="col-12">
          <nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">  
    <a class="navbar-brand" href="#">Hospital management</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'patient:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#row3">About us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#row5">Contact us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'patient:list'  %}">Booking confirmation</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'patient:login'  %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'patient:booking' %}">Booking</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'doctor:doctorlogin' %}">Doctor login</a>
        </li>
        
        
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
        </div>
      </div>
{% block content %}
      <div class="row" id="row2">
        <div class="col-12">
          <h1>AZPEN HOSPITAL</h1>
        </div>
      </div>
      <div class="row" id="row3">
        <h2>About Us</h2>
        <p>A hospital is a healthcare institution providing patient treatment with specialized health science and auxiliary healthcare staff and medical equipment.[1] The best-known type of hospital is the general hospital, which typically has an emergency department to treat urgent health problems ranging from fire and accident victims to a sudden illness. A district hospital typically is the major health care facility in its region, with many beds for intensive care and additional beds for patients who need long-term care.

          Specialized hospitals include trauma centers, rehabilitation hospitals, children's hospitals, geriatric hospitals, and hospitals for specific medical needs, such as psychiatric hospitals for psychiatric treatment and other disease-specific categories. Specialized hospitals can help reduce health care costs compared to general hospitals.[2] Hospitals are classified as general, specialty, or government depending on the sources of income received.Hospitals are currently staffed by professional physicians, surgeons, nurses, and allied health practitioners. In the past, however, this work was usually performed by the members of founding religious orders or by volunteers. However, there are various Catholic religious orders, such as the Alexians and the Bon Secours Sisters that still focus on hospital ministry in the late 1990s, as well as several other Christian denominations, including the Methodists and Lutherans, which run hospitals.[4] In accordance with the original meaning of the word, hospitals were original "places of hospitality", and this meaning is still preserved in the names of some institutions such as the Royal Hospital Chelsea, established in 2023 as a retirement and nursing home for veteran soldiers.</p>

      </div>
      <div class="row" id="row4">
        <div class="col-3"><div class="card" style="width: 18rem;">
          <img src="{% static 'image/doctor1.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Dr Sara</h5>
            <p class="card-text">Iam Dr Sara specializes in everything having to do with those parts of the body. They even perform operations.</p>
            <a href="#" class="btn btn-primary">Booking</a>
          </div>
        </div></div>
        <div class="col-3"><div class="card" style="width: 18rem;">
          <img src="{% static 'image/doctor2.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Dr Anjali</h5>
            <p class="card-text"> Iam Dr Anjali  who focuses on the health of infants, children, adolescents and young adults.</p>
            <a href="#" class="btn btn-primary">Booking</a>
          </div>
        </div></div>
        <div class="col-3"><div class="card" style="width: 18rem;">
          <img src="{% static 'image/doctor3.avif' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Dr Robert</h5>
            <p class="card-text">Iam  Dr robert   a physician who specializes in the diagnosis and surgical treatment. </p>
            <a href="#" class="btn btn-primary">Booking</a>
          </div>
        </div></div>
        <div class="col-3"><div class="card" style="width: 18rem;">
          <img src="{% static 'image/doctor4.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title">Dr Carlos</h5>
            <p class="card-text"> Iam Dr Carlos   Orthopedic surgeons diagnose and treat conditions affecting your bones, muscles, and joints. </p>
            <a href="#" class="btn btn-primary">Booking</a>
          </div>
        </div></div>
      </div>
      <div class="row" id="row5">
        <h2>contact us</h2>
        <div class="mb-3">
  <label for="formGroupExampleInput" class="form-label">Patient Name</label>
  <input type="text" class="form-control" id="formGroupExampleInput" placeholder="">
</div>
<div class="mb-3">
  <label for="formGroupExampleInput2" class="form-label">Address</label>
  <input type="text" class="form-control" id="formGroupExampleInput2" placeholder=""><br>
  <button type="button" class="btn btn-primary">Submit</button>
</div>
      </div>
      </div>
{% endblock %}

    </div>





<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

patient/templates/patient/list.html
{% extends 'patient/home.html' %}
{% block content %}
<h1>Booking List</h1>
<div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <table class="table">
            <thead>
              <tr>
                <th scope="col">name</th>
                <th scope="col">date</th>
                <th scope="col">time</th>
                <th scope="col">doctor</th>
                <th>status</th>
              </tr>
            </thead>
            <tbody>
                {% for i in patient %}
              <tr>
                <th scope="row">{{i.name}}</th>
                <td>{{i.date}}</td>
                <td>{{i.time}}</td>
                <td>{{i.doctor}}</td>
                <td>{{i.status}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
    </div>
    <div class="col-3"></div>
</div>
{% endblock %}

patient/templates/patient/login.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid">

    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Hospital management</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'patient:home' %}">Home</a>
                </li>
                
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'patient:login'  %}">Login</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'patient:booking'  %}">Booking</a>
                </li>



              </ul>
              <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
              </form>
            </div>
          </div>
        </nav>
      </div>
    </div>
    <div class="row">
      <div class="col-4"></div>
      <div class="col-4">
        <h2>login</h2>
        <form method="post">
          {% csrf_token %}
          <div class="mb-3">
            <label for="exampleInputEmail1" class="form-label">Email address</label>
            <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
            <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
          </div>
          <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword1" name="password">
          </div>
          <div class="mb-3 form-check">
            <label class="form-check-label" for="exampleCheck1">if u dont have any acc</label>
            <a href="{% url 'patient:signup' %}">register here</a>
          </div>
          <div class="mb-3 form-check">
            <label class="form-check-label" for="exampleCheck1"><p style="color: red;">{{msg}}</p></label>
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
      <div class="col-4"></div>
    </div>
    
  </div>
  </div>
  </div>





  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>
{% block content %}

{% endblock %}

patient/templates/patient/signup.html
{% extends 'patient/home.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="row">
       <div class="col-4"></div>
       <div class="col-4">
        <form method="post">
          {% csrf_token %}
            <h1>signup</h1>
           
            <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Full Name</label>
                <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="name">
              </div> <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
                <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
              </div>
            <div class="mb-3">
              <label for="exampleInputPassword1" class="form-label">Password</label>
              <input type="password" class="form-control" id="exampleInputPassword1" name="password">
            </div>
        
        <div class="mb-3">
            <label for="exampleInputPassword1" class="form-label"> conformPassword</label>
            <input type="password" class="form-control" id="exampleInputPassword1">
          </div>
              <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>
              <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
       </div>
       <div class="col-4"></div>
    </div>
</body>
</html>
{% endblock %}